exclude: '.venv|__pycache__|tests/dev/|tests/fixtures/|core/static/'
include: 'core/static/app/'

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files
            args: ['--maxkb=10000']
          - id: check-case-conflict
          - id: check-xml
          - id: check-yaml
          - id: check-json
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.21.2
      hooks:
          - id: pyupgrade
            args: [--py312-plus]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.16.10
      hooks:
          - id: ruff-check
            args: [--fix]
          - id: ruff-format

ci:
    autoupdate_schedule: quarterly
    skip: []
    submodules: false
